
let bigBoy = [
    //batch 1
    ["Learning Resources", "BookBank", "https://github.com/ajitpal/BookBank"],
    ["Software Best Practices", "Heroku Alternatives", "herokuAlternatives"],
    ["Career Development & Productivity", "findHiringManagerLinkedin", "Use this Google search to find hiring managers on Linked in"],
    ["Interactive Learning & Tools", "shareCodeOnDiscord", "Sharing code on Discord"],
    ["Career Development & Productivity", "The PERFECT Daily Posture Routine", "https://www.youtube.com/watch?v=h3PZZyoXnKU&ab_channel=ATHLEAN-X%E2%84%A2"],
    ["Career Development & Productivity", "Daily Mobility Routine", "https://www.youtube.com/watch?v=SsT_go-oCcQ&ab_channel=AlanThrall%28UntamedStrength%29"],
    ["Career Development & Productivity", "Exercises for gamers", "https://www.youtube.com/playlist?list=PLoitz_8LdhuxK227095QhzLI-USOrzUGs"],
    ["Web Design", "webAccessibility", "Practice web accessibility"],
    ["Learning Resources", "Markdown tutorial", "https://commonmark.org/help/tutorial/"],
    ["Learning Resources", "MDN", "https://developer.mozilla.org/en-US/"],
    ["Web Design", "SVG Icons as React Components", "https://reactsvgicons.com/"],
    ["Interactive Learning & Tools", "Anki", "ankiweb.net"],
    ["Learning Resources", "Learning How to Learn", "https://www.coursera.org/learn/learning-how-to-learn"],
    ["Interactive Learning & Tools", "Study with Me + Anki Flashcard Method", "https://www.youtube.com/watch?v=W-EpiaPcgTk&ab_channel=AliAbdaal"],
    ["Software Best Practices", "Archived Atom Text Editor", "https://github.blog/news-insights/product-news/sunsetting-atom/"],
    ["Web Design", "Unsplash", "https://unsplash.com/"],
    ["Software Best Practices", "Live Server for Visual Studio", "https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer"],
    ["Career Development & Productivity", "Outline of HTWFIP", "Outline of How to Win Friends & Influence People"],
    ["Career Development & Productivity", "How to Win Friends & Influence People - Audio File", "https://archive.org/details/HowToWinFriendsInfluencePeople/HowToWinFriendsInfluencePeople-DaleCarnegie01Of.mp3"],
    ["Web Design", "Browsersync", "browsersync.io"],
    ["Learning Resources", "Learn to Code HTML & CSS", "shayhowe.com"],
    ["Learning Resources", "Leon Noel slides", "https://slides.com/leonnoel/"],
    ["Learning Resources", "r/learnprogramming", "https://www.reddit.com/r/learnprogramming/wiki/index/#wiki_related_communities"],
    ["Learning Resources", "Hacker News", "https://news.ycombinator.com/news"],
    ["Learning Resources", "Skill Share", "https://www.skillshare.com/en/browse"],
    ["Web Design", "flexbox.io", "https://flexbox.io/"],
    ["Web Design", "CSS Flexbox Layout Guide", "https://css-tricks.com/snippets/css/a-guide-to-flexbox/"],
    ["Interactive Learning & Tools", "Flexbox Zombies", "https://geddski.teachable.com/p/flexbox-zombies"],
    ["Learning Resources", "Automate the Boring Stuff with Python", "https://www.reddit.com/r/learnprogramming/comments/ikocut/automate_the_boring_stuff_with_python_online/?utm_medium=android_app&utm_source=share"],
    ["Career Development & Productivity", "Grokking the Modern System Design Interview", "https://www.educative.io/courses/grokking-the-system-design-interview"],
    ["Software Best Practices", "The Pragmatic Programmer", "https://www.amazon.com/dp/020161622X"],
    ["Career Development & Productivity", "Cracking the Coding Interview", "https://www.amazon.com/Cracking-Coding-Interview-Programming-Questions/dp/0984782850"],
    ["Software Best Practices", "Semicolons in JavaScript", "https://flaviocopes.com/javascript-automatic-semicolon-insertion/"],
    ["Learning Resources", "Eloquent JavaScript", "https://www.amazon.com/dp/1593272820"],
    ["Learning Resources", "List of coding Resources compiled by Alissa", "https://drive.google.com/file/d/1XKgoq6WjgIdL1PyALjJReW5djQLlhJ/view"],
    ["Learning Resources", "UBCx: How to Code: Simple Data", "https://www.edx.org/learn/coding/university-of-british-columbia-how-to-code-simple-data"],
    ["Learning Resources", "UBCx: How to Code: Complex Data", "https://www.edx.org/learn/coding/university-of-british-columbia-how-to-code-complex-data"],
    ["Interactive Learning & Tools", "javascript30", "https://javascript30.com/"],
    ["Interactive Learning & Tools", "Simple Programming Problems", "https://adriann.github.io/programming_problems.html"],
    ["Career Development & Productivity", "Hand & Wrist Exercises For Gamers!", "https://www.youtube.com/watch?v=wYGfDCGrJ4A&ab_channel=DrLeviHarrison"],
    ["Learning Resources", "JavaScript Crash Course For Beginners", "https://www.youtube.com/watch?v=hdI2bqOjy3c&ab_channel=TraversyMedia"],
    ["Web Design", "Fundamentals of Web apps", "https://fullstackopen.com/en/part0/fundamentals_of_web_apps"],
    ["Learning Resources", "Hard Coding Concepts Explained with Simple Real-life Analogies", "https://medium.com/edge-coders/hard-coding-concepts-explained-with-simple-real-life-analogies-280635e98e37"],
    ["Interactive Learning & Tools", "AnkiDroid Flashcards", "https://play.google.com/store/apps/details?id=com.ichi2.anki"],
    ["Interactive Learning & Tools", "Free AnkiDroid Alternatives for iPhone", "https://alternativeto.net/software/ankidroid/?license=free&platform=iphone"],
    ["Interactive Learning & Tools", "AnkiApp", "https://www.ankiapp.com/"],
    ["Interactive Learning & Tools", "AnkiApp Flashcards on Mac App Store", "https://apps.apple.com/us/app/ankiapp-flashcards/id689185915"],
    ["Interactive Learning & Tools", "Anki Flashcards maker on the App Store", "https://apps.apple.com/us/app/anki-flashcards-maker/id1219764607"],
    ["Interactive Learning & Tools", "AnkiMobile Flashcards on the App Store", "https://apps.apple.com/us/app/ankimobile-flashcards/id373493387"],
    ["Learning Resources", "Learn to Code", "https://www.w3schools.com/"],
    ["Software Best Practices", "Why Python Has Become a Popular Choice for Mobile App Development", "https://dzone.com/articles/why-python-has-become-a-popular-choice-for-mobile"],
    ["Learning Resources", "Learn web development as an absolute beginner", "https://www.youtube.com/watch?v=ysEN5RaKOlA&ab_channel=CoderCoder"],
    ["Learning Resources", "Learning how to learn", "https://www.lesswrong.com/posts/qLqyPMfc8epav72JF/learning-how-to-learn?ref=briefingday.com&curator=briefingday.com&utm_source=briefingday.com&utm_medium=email"],
    ["Learning Resources", "Automate the Boring Stuff with Python", "https://automatetheboringstuff.com/"],
    ["Learning Resources", "Think Python, 2nd edition", "https://greenteapress.com/wp/think-python-2e/"],
    ["Career Development & Productivity", "The Google History of a High-Paid Sr. Engineer", "https://www.youtube.com/watch?v=LW9pT246LrI&ab_channel=ColtSteele"],
    ["Career Development & Productivity", "The happier workspace", "https://www.notion.com/"],
    ["Interactive Learning & Tools", "Project Jupyter", "https://jupyter.org/"],
    ["Software Best Practices", "Arrow Functions vs Functions", "https://stackoverflow.com/questions/34361379/are-arrow-functions-and-functions-equivalent-interchangeable"],
    ["Software Best Practices", "3dev-fullstack", "https://github.com/threedevs/3dev-fullstack?tab=readme-ov-file"],
    ["Software Best Practices", "Visual Studio Code Keyboard shortcuts for Windows", "keyboard-shortcuts-windows"],
    ["Learning Resources", "What the heck is the event loop anyway?", "https://www.youtube.com/watch?v=8aGhZQkoFbQ&ab_channel=JSConf"],
    ["Interactive Learning & Tools", "Archived Grepper", "https://chromewebstore.google.com/detail/grepper/amaaokahonnfjjemodnpmeenfpnnbkco?hl=en"],
    ["Interactive Learning & Tools", "The Query & Answer System for the Ambitious Developer", "https://www.grepper.com/"],
    ["Learning Resources", "Learning JavaScript Design Patterns", "https://patterns.addy.ie/"],
    ["Learning Resources", "Full React Course 2020", "https://www.youtube.com/watch?v=4UZrsTqkcW4&ab_channel=freeCodeCamp.org"],
    ["Career Development & Productivity", "Events and Webinars", "https://www.mongodb.com/events"],
    ["Learning Resources", "Coyotiv Public Lecture Series", "https://www.meetup.com/coyotiv-school-of-software-engineering/events/273778665/?_xtd=gqFyqTI2NTcxNjUxOKFwpmlwaG9uZQ%253D%253D&from=ref"],
    ["Career Development & Productivity", "Why Terrifying Self-Discovery Is the Only Way to Succeed", "https://podcasts.apple.com/us/podcast/why-terrifying-self-discovery-is-the-only-way-to/id1317823455?i=1000465812514"],
    ["Web Design", "Code Guide", "https://codeguide.co/"],
    ["Learning Resources", "Data Structures and Algorithms in JavaScript", "https://www.youtube.com/watch?v=t2CEgPsws3U&ab_channel=freeCodeCamp.org"],
    ["Career Development & Productivity", "CV Compiler", "https://cvcompiler.com/"],
    ["Learning Resources", "You Don't Know JS", "https://github.com/getify/You-Dont-Know-JS/tree/1st-ed"],
    ["Web Design", "CSS Flexbox vs CSS Grid", "https://github.com/getify/You-Dont-Know-JS/tree/1st-ed"],
    ["Software Best Practices", "Agile Web Development and Scrum", "https://www.bright.global/en/blog/agile-web-development-and-scrum"],
    ["Web Design", "Inaccessible websites? - it's you, not JavaScript", "https://www.youtube.com/watch?v=J42a3SP9obY&ab_channel=JSConf"],
    ["Career Development & Productivity", "Waking up App", "https://dynamic.wakingup.com/redeemMonth/b283c7?optionValue=1&button=give_the_app"],
    ["Career Development & Productivity", "20 JavaScript questions you’ll be asked in your next interview", "https://thenextweb.com/news/here-are-the-20-javascript-questions-youll-be-asked-in-your-next-interview-syndicaton"],
    ["Career Development & Productivity", "Are You Suffering From Impostor Syndrome?", "https://www.visualcapitalist.com/are-you-suffering-from-impostor-syndrome/"],
    ["Career Development & Productivity", "How to Get Hired Virtually", "HireClub. How_to_Get_Hired_Virtually"],
    ["Learning Resources", "Empovia", "https://www.youtube.com/channel/UCOO_853KC58BoP7rdoAG5dA"],
    ["Career Development & Productivity", "Advanced Problem Solving Secrets for Technical Interviews", "https://docs.google.com/presentation/d/1NckKPIFB1EHgsw-RxmvVrcDwJtau4IJmTO8VuJKHVXw/edit#slide=id.ga1b4ea10f0_0_36"]

    //batch 2
]
